name: Style

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  comments:
    uses: junkerderprovinz/junkerderprovinz/.github/workflows/comment-style.yml@304a79d2958573589262579e024eed8ef7218689 # main
