name: Style

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  comments:
    uses: junkerderprovinz/junkerderprovinz/.github/workflows/comment-style.yml@ef08ae65107775a608940d32204c24d5cbde769d # main
